import { useEffect, useState } from 'react'
import { FiActivity, FiAlertTriangle, FiBarChart2, FiBox, FiChevronRight, FiDollarSign, FiEdit2, FiGrid, FiLogOut, FiMenu, FiPackage, FiPlus, FiSearch, FiShoppingBag, FiTrash2, FiTrendingUp, FiUsers, FiX } from 'react-icons/fi'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import navLogo from '../assets/logo/navLogo.PNG'
import './Commerce.css'

const blank={title:'',brand:'',price:'',stock:'',thumbnail_url:'',storage:'',color:'',description:''}
const states=['pending','confirmed','processing','shipped','out_for_delivery','delivered','cancelled']
const money=n=>`₦${Number(n||0).toLocaleString()}`
const nice=s=>String(s||'').replaceAll('_',' ')

export default function Admin(){
 const {isAdmin,loading}=useAuth(); const [tab,setTab]=useState('overview'); const [orders,setOrders]=useState([]); const [products,setProducts]=useState([]); const [profiles,setProfiles]=useState([]); const [items,setItems]=useState([]); const [q,setQ]=useState(''); const [filter,setFilter]=useState('all'); const [selected,setSelected]=useState(null); const [editing,setEditing]=useState(false); const [form,setForm]=useState(blank); const [notice,setNotice]=useState(''); const [menuOpen,setMenuOpen]=useState(false)
 const load=async()=>{if(!supabase||!isAdmin)return;const [o,p,c,i]=await Promise.all([supabase.from('orders').select('*').order('created_at',{ascending:false}),supabase.from('products').select('*').order('created_at',{ascending:false}),supabase.from('profiles').select('*').order('created_at',{ascending:false}),supabase.from('order_items').select('*')]);setOrders(o.data||[]);setProducts(p.data||[]);setProfiles((c.data||[]).filter(x=>x.role!=='admin'));setItems(i.data||[])}
 useEffect(()=>{load()},[isAdmin])
 useEffect(()=>{document.body.style.overflow=menuOpen?'hidden':'';return()=>{document.body.style.overflow=''}},[menuOpen])
 const active=orders.filter(o=>o.status!=='cancelled'); const revenue=active.reduce((s,o)=>s+Number(o.total||0),0); const low=products.filter(p=>Number(p.stock)<=5); const customers=profiles
 const filteredOrders=orders.filter(o=>{const x=q.toLowerCase();return(!x||[o.order_number,o.shipping_name,o.shipping_email,o.shipping_phone].some(v=>String(v||'').toLowerCase().includes(x)))&&(filter==='all'||o.status===filter)})
 const filteredProducts=products.filter(p=>!q||[p.title,p.brand,p.storage].some(v=>String(v||'').toLowerCase().includes(q.toLowerCase())))
 const filteredCustomers=customers.filter(c=>!q||[c.full_name,c.email].some(v=>String(v||'').toLowerCase().includes(q.toLowerCase())))
 const updateOrder=async(o,patch)=>{const {error}=await supabase.from('orders').update(patch).eq('id',o.id);if(error)return setNotice(error.message);if(patch.status&&patch.status!==o.status)await supabase.from('tracking_events').insert({order_id:o.id,status:nice(patch.status),note:`Order status changed to ${nice(patch.status)}.`});setNotice('Order updated');load()}
 const removeOrder=async o=>{if(!confirm(`Delete ${o.order_number}?`))return;const {error}=await supabase.from('orders').delete().eq('id',o.id);if(error)setNotice(error.message);else{setSelected(null);setNotice('Order deleted');load()}}
 const saveProduct=async e=>{e.preventDefault();const payload={...form,price:Number(form.price),stock:Number(form.stock)};const {error}=editing?await supabase.from('products').update(payload).eq('id',editing):await supabase.from('products').insert(payload);if(error)return setNotice(error.message);setNotice(editing?'Product updated':'Product created');setForm(blank);setEditing(false);load()}
 const nav=[['overview','Overview',FiGrid],['orders','Orders',FiPackage],['products','Products',FiBox],['customers','Customers',FiUsers],['analytics','Analytics',FiBarChart2]]
 const chooseTab=id=>{setTab(id);setQ('');setMenuOpen(false)}
 if(loading)return <main className="admin-shell"><div className="admin-loading">Loading control centre…</div></main>
 if(!isAdmin)return <main className="admin-shell"><div className="admin-loading"><FiUsers/><h1>Admin access required.</h1><p>Sign in with an account with the admin role.</p></div></main>
 return <main className="admin-shell"><aside className={`admin-sidebar ${menuOpen?'menu-open':''}`}><div className="admin-brand"><img src={navLogo} alt="Phone Hub"/><div><strong>PHONE HUB</strong><small>CONTROL CENTRE</small></div></div><button className="admin-menu-close" onClick={()=>setMenuOpen(false)} aria-label="Close menu"><FiX/></button><nav>{nav.map(([id,name,Icon])=><button className={tab===id?'active':''} onClick={()=>chooseTab(id)} key={id}><Icon/><span>{name}</span>{tab===id&&<FiChevronRight/>}</button>)}</nav><div className="admin-bottom"><span><i/> SYSTEM OPERATIONAL</span><button onClick={()=>supabase.auth.signOut()}><FiLogOut/> Sign out</button></div></aside><section className="admin-main"><header className="admin-mobile-bar"><img src={navLogo} alt="Phone Hub"/><button onClick={()=>setMenuOpen(true)} aria-label="Open menu"><FiMenu/></button></header><header className="admin-top"><div><span>PHONE HUB / ADMIN</span><h1>{tab==='overview'?'Command centre.':nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="admin-live">● LIVE <button onClick={load}><FiActivity/></button></div></header>{notice&&<button className="admin-notice" onClick={()=>setNotice('')}>{notice}<FiX/></button>}
 {tab==='overview'&&<Overview revenue={revenue} orders={orders} customers={customers} products={products} low={low} setTab={setTab} setSelected={setSelected}/>} 
 {tab==='orders'&&<section className="admin-content"><Toolbar q={q} setQ={setQ} placeholder="Search orders…"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option>{states.map(s=><option key={s} value={s}>{nice(s)}</option>)}</select></Toolbar><div className="admin-table"><div className="table-head"><span>ORDER</span><span>CUSTOMER</span><span>AMOUNT</span><span>STATUS</span><span>DATE</span></div>{filteredOrders.map(o=><button className="table-row" key={o.id} onClick={()=>setSelected(o)}><b>{o.order_number}</b><span>{o.shipping_name||'Guest'}</span><span>{money(o.total)}</span><Status s={o.status}/><span>{new Date(o.created_at).toLocaleDateString()}</span><FiChevronRight/></button>)}{!filteredOrders.length&&<Empty text="No orders found."/>}</div></section>}
 {tab==='products'&&<section className="admin-content"><Toolbar q={q} setQ={setQ} placeholder="Search catalogue…"><button className="admin-primary" onClick={()=>{setEditing(true);setForm(blank)}}><FiPlus/> Add product</button></Toolbar><div className="product-layout"><div className="admin-table product-table">{filteredProducts.map(p=><div className="product-row" key={p.id}><img src={p.thumbnail_url} alt=""/><div><b>{p.title}</b><span>{p.brand} · {p.storage||'Standard'}</span></div><strong>{money(p.price)}</strong><span className={Number(p.stock)<=5?'stock-low':''}>{p.stock} in stock</span><button onClick={()=>{setEditing(p.id);setForm({...blank,...p})}}><FiEdit2/></button><button onClick={async()=>{if(confirm('Delete this product?')){const {error}=await supabase.from('products').delete().eq('id',p.id);if(error)setNotice(error.message);else load()}}}><FiTrash2/></button></div>)}{!filteredProducts.length&&<Empty text="No products found."/>}</div>{editing!==false&&<Editor form={form} setForm={setForm} editing={editing} save={saveProduct} close={()=>{setEditing(false);setForm(blank)}}/>}</div></section>}
 {tab==='customers'&&<section className="admin-content"><Toolbar q={q} setQ={setQ} placeholder="Search customers…"/><div className="admin-table"><div className="table-head"><span>CUSTOMER</span><span>EMAIL</span><span>ORDERS</span><span>SPENT</span><span>JOINED</span></div>{filteredCustomers.map(c=>{const mine=orders.filter(o=>o.user_id===c.id),spent=mine.filter(o=>o.status!=='cancelled').reduce((s,o)=>s+Number(o.total||0),0);return <div className="table-row static" key={c.id}><b>{c.full_name||'Unnamed'}</b><span>{c.email}</span><span>{mine.length}</span><span>{money(spent)}</span><span>{new Date(c.created_at).toLocaleDateString()}</span></div>})}{!filteredCustomers.length&&<Empty text="No customers found."/>}</div></section>}
 {tab==='analytics'&&<Analytics orders={orders} items={items} revenue={revenue}/>} </section>{selected&&<Drawer order={selected} close={()=>setSelected(null)} update={updateOrder} remove={removeOrder}/>}</main>
}
function Metric({icon:Icon,label,value,sub,accent}){return <div className={`metric ${accent?'accent':''}`}><Icon/><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Overview({revenue,orders,customers,products,low,setTab,setSelected}){const delivered=orders.filter(o=>o.status==='delivered').length;return <section className="admin-content"><div className="admin-welcome"><div><span>STORE PERFORMANCE</span><h2>Good evening, Iman<span>.</span></h2><p>Your store is moving. Here's the pulse of Phone Hub.</p></div><div className="orbit"><FiTrendingUp/><b>LIVE</b><small>store pulse</small></div></div><div className="metrics"><Metric icon={FiDollarSign} label="Total revenue" value={money(revenue)} sub="Non-cancelled orders" accent/><Metric icon={FiShoppingBag} label="Orders" value={orders.length} sub={`${delivered} delivered`}/><Metric icon={FiUsers} label="Customers" value={customers.length} sub="Registered customers"/><Metric icon={FiAlertTriangle} label="Low stock" value={low.length} sub="5 units or less"/></div><div className="dashboard-grid"><section className="panel"><Panel title="Revenue pulse" meta="STORE PERFORMANCE"/><div className="pulse"><svg viewBox="0 0 700 220" preserveAspectRatio="none"><path d="M0 180 C80 170 90 115 160 145 S250 175 310 110 S400 125 455 80 S550 110 610 45 S665 55 700 20"/></svg><div><span>JAN</span><span>MAR</span><span>MAY</span><span>JUL</span><span>SEP</span></div></div></section><section className="panel"><Panel title="Order pipeline" meta={`${orders.length} TOTAL`}/>{['pending','processing','shipped','out_for_delivery','delivered'].map(s=>{const n=orders.filter(o=>o.status===s).length,p=orders.length?n/orders.length*100:0;return <div className="pipeline" key={s}><span>{nice(s)}</span><div><i style={{width:`${Math.max(2,p)}%`}}/></div><b>{n}</b></div>})}</section></div><div className="dashboard-grid"><section className="panel"><Panel title="Recent orders" meta="VIEW ALL" action={()=>setTab('orders')}/>{orders.slice(0,5).map(o=><button className="mini-order" key={o.id} onClick={()=>setSelected(o)}><span><b>{o.order_number}</b><small>{o.shipping_name||'Guest'}</small></span><strong>{money(o.total)}</strong><Status s={o.status}/></button>)}{!orders.length&&<Empty text="No orders yet."/>}</section><section className="panel"><Panel title="Stock watch" meta={`${low.length} ALERTS`} action={()=>setTab('products')}/>{low.slice(0,5).map(p=><div className="stock" key={p.id}><span><b>{p.title}</b><small>{p.brand}</small></span><strong>{p.stock} left</strong></div>)}{!low.length&&<Empty text="Inventory looks healthy."/>}</section></div></section>}
function Analytics({orders,items,revenue}){const avg=orders.length?revenue/orders.filter(o=>o.status!=='cancelled').length:0;const best=Object.entries(items.reduce((a,i)=>{a[i.title]=(a[i.title]||0)+Number(i.quantity||0);return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,7);return <section className="admin-content"><div className="analytics-banner"><div><span>BUSINESS INTELLIGENCE</span><h2>The numbers behind the store.</h2></div><div><small>AVERAGE ORDER</small><b>{money(avg)}</b></div><div><small>DELIVERED</small><b>{orders.filter(o=>o.status==='delivered').length}</b></div></div><div className="dashboard-grid"><section className="panel"><Panel title="Best sellers" meta="UNITS SOLD"/>{best.map(([n,v],i)=><div className="rank" key={n}><b>0{i+1}</b><span>{n}</span><strong>{v} units</strong></div>)}{!best.length&&<Empty text="Sales data will appear here."/>}</section><section className="panel"><Panel title="Sales by status" meta="CURRENT ORDERS"/>{states.map(s=><div className="sales" key={s}><span>{nice(s)}</span><strong>{money(orders.filter(o=>o.status===s).reduce((n,o)=>n+Number(o.total||0),0))}</strong></div>)}</section></div></section>}
function Toolbar({q,setQ,placeholder,children}){return <div className="toolbar"><div><FiSearch/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={placeholder}/></div>{children}</div>}
function Panel({title,meta,action}){return <div className="panel-title"><h3>{title}</h3><button onClick={action}>{meta}{action&&<FiChevronRight/>}</button></div>}
function Status({s}){return <span className={`status ${s}`}><i/>{nice(s)}</span>}
function Empty({text}){return <div className="empty">{text}</div>}
function Editor({form,setForm,editing,save,close}){return <section className="editor"><div className="panel-title"><h3>{editing&&editing!==true?'Edit product':'New product'}<button onClick={close}><FiX/></button></div><form onSubmit={save}>{['title','brand','price','stock','thumbnail_url','storage','color'].map(k=><label key={k}>{k.replace('_',' ')}<input required={['title','brand','price','stock','thumbnail_url'].includes(k)} type={['price','stock'].includes(k)?'number':'text'} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Description<textarea rows="4" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="admin-primary">{editing&&editing!==true?'Save changes':'Create product'}</button></form></section>}
function Drawer({order,close,update,remove}){const [tracking,setTracking]=useState(order.tracking_number||''),[courier,setCourier]=useState(order.courier||'');return <div className="drawer-bg" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span>ORDER DETAILS</span><h2>{order.order_number}</h2></div><button onClick={close}><FiX/></button></div><Status s={order.status}/><section><small>CUSTOMER</small><b>{order.shipping_name||'Guest'}</b><p>{order.shipping_email||'—'}<br/>{order.shipping_phone||'—'}</p></section><section><small>DELIVERY</small><p>{order.shipping_address||'—'}<br/>{order.shipping_city||''}</p></section><label>Status<select value={order.status} onChange={e=>update(order,{status:e.target.value})}>{states.map(s=><option key={s} value={s}>{nice(s)}</option>)}</select></label><label>Tracking<input value={tracking} onChange={e=>setTracking(e.target.value)} onBlur={()=>update(order,{tracking_number:tracking||null})}/></label><label>Courier<input value={courier} onChange={e=>setCourier(e.target.value)} onBlur={()=>update(order,{courier:courier||null})}/></label><div className="drawer-total"><span>Total</span><b>{money(order.total)}</b></div><button className="danger" onClick={()=>remove(order)}><FiTrash2/> Delete order</button></aside></div>}
