import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { FiEye, FiEyeOff, FiArrowLeft, FiLock, FiMail, FiUser, FiMoon, FiSun } from 'react-icons/fi'
import { useAuth } from '../context/AuthContext'
import './Auth.css'

export default function SignupReal({ darkMode, setDarkMode }) {
  const navigate = useNavigate(); const location = useLocation(); const { signUp } = useAuth()
  const [form,setForm]=useState({name:'',email:'',password:''}); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('')
  const redirect = new URLSearchParams(location.search).get('redirect') || '/'
  const submit=async(e)=>{e.preventDefault();setError('');setMessage('');setBusy(true);try{const data=await signUp(form);if(data.session)navigate(redirect,{replace:true});else setMessage('Account created. Check your email to confirm your account, then sign in.')}catch(err){setError(err.message||'Unable to create account.')}finally{setBusy(false)}}
  return <main className="auth-page"><div className="auth-topbar"><Link to="/" className="auth-back"><FiArrowLeft/> Back</Link><button className="auth-theme-toggle" onClick={()=>setDarkMode(!darkMode)}>{darkMode?<FiSun/>:<FiMoon/>}</button></div><section className="auth-card"><div className="auth-brand"><span>PHONE</span>HUB</div><p className="auth-eyebrow">JOIN PHONEHUB</p><h1 className="auth-title">Create your account.</h1><p className="auth-subtitle">An account is required before you can checkout or track an order.</p>{error&&<div className="commerce-error">{error}</div>}{message&&<div className="commerce-success-inline">{message}</div>}<form onSubmit={submit} className="auth-form"><label>Full name</label><div className="auth-input-wrap"><FiUser/><input name="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><label>Email address</label><div className="auth-input-wrap"><FiMail/><input name="email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div><label>Password</label><div className="auth-input-wrap"><FiLock/><input name="password" type={show?'text':'password'} minLength="6" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><button type="button" className="password-toggle" onClick={()=>setShow(!show)}>{show?<FiEyeOff/>:<FiEye/>}</button></div><label className="terms"><input type="checkbox" required/> I agree to the terms and privacy policy.</label><button className="auth-submit" disabled={busy}>{busy?'Creating account…':'Create account'}</button></form><p className="auth-switch">Already have an account? <Link to={`/login${redirect!=='/'?`?redirect=${encodeURIComponent(redirect)}`:''}`}>Sign in</Link></p></section></main>
}
